# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3234f02d851d1d4d12aa4ff542f884d528f34afc45fdd02243c6ab2c21dbdb3519074b463b5619d2b7413c231957f7d13ee389aeafe7dfc1c0c6cc0b66f0a285

test:
  secret_key_base: 9fd9db909d2192468d4ee4409889926118d27e625f317a762d73e6fe2ffcdfd2d7e425627041236c505bc399e5b0797957b14dc9881103ccf7a2081225d1f73f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
